GET http://localhost:3001/api/persons/

###
POST http://localhost:3001/api/persons/
content-type: application/json

{
    "name": "Glen Flenderson",
    "number": "312-123-634598"
} 

###

GET http://localhost:3001/api/persons/646c96b20fb47a7f6ed8f194

### 
DELETE http://localhost:3001/api/persons/646c96b20fb47a7f6ed8f194/
